using System.Xml.Serialization;

namespace DataContracts.MassTransit;

[XmlType(AnonymousType = true, Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request"),
 XmlRoot(ElementName = "CrackHashManagerRequest", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
public interface ISendWorkerTask
{
    // <summary>
    /// GUID запроса
    /// </summary>
    [XmlElement("PartNumber", ElementName = "PartNumber")]
    public string RequestId { get; set; }

    /// <summary>
    /// Номер части запроса
    /// </summary>
    [XmlElement("PartNumber", ElementName = "PartNumber")]
    public int PartNumber { get; set; }

    /// <summary>
    /// Общее количество частей
    /// </summary>
    [XmlElement("PartCount", ElementName = "PartCount")]
    public int PartCount { get; set; }

    /// <summary>
    /// Хэш
    /// </summary>
    [XmlElement("Hash", ElementName = "Hash")]
    public string Hash { get; set; }

    /// <summary>
    /// Максимальная длина последовательности
    /// </summary>
    [XmlElement("MaxLength", ElementName = "MaxLength")]
    public int MaxLength { get; set; }

    /// <summary>
    /// Алфавит для генерации строк
    /// </summary>
    [XmlElement("Alphabet", ElementName = "Alphabet")]
    public Alphabet Alphabet { get; set; }
}

public class Alphabet
{
    public Alphabet(char[] symbols)
    {
        Symbols = symbols;
    }

    [XmlElement("Symbols", ElementName = "symbols")]
    public char[] Symbols { get; set; }
}


//------------------------------------------------------------------------------
// https://minify-beautify.com/convert-xsd-to-c-sharp-class-online/
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.210.0.

// [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.210.0")]
// [Serializable]
// [System.Xml.Serialization.XmlTypeAttribute("CrackHashManagerRequest", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request", AnonymousType = true)]
// [System.ComponentModel.DesignerCategoryAttribute("code")]
// [System.Xml.Serialization.XmlRootAttribute("CrackHashManagerRequest", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
// public class CrackHashManagerRequest
// {
//     [System.Xml.Serialization.XmlElementAttribute("RequestId", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     public string RequestId { get; set; }
//
//     [System.Xml.Serialization.XmlElementAttribute("PartNumber", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     public int PartNumber { get; set; }
//
//     [System.Xml.Serialization.XmlElementAttribute("PartCount", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     public int PartCount { get; set; }
//
//     [System.Xml.Serialization.XmlElementAttribute("Hash", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     public string Hash { get; set; }
//
//     [System.Xml.Serialization.XmlElementAttribute("MaxLength", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     public int MaxLength { get; set; }
//
//     [System.Xml.Serialization.XmlIgnoreAttribute]
//     private System.Collections.ObjectModel.Collection<string> _alphabet;
//
//     [System.Xml.Serialization.XmlArrayAttribute("Alphabet", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     [System.Xml.Serialization.XmlArrayItemAttribute("symbols", Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     public System.Collections.ObjectModel.Collection<string> Alphabet
//     {
//         get => _alphabet;
//         private set => _alphabet = value;
//     }
//
//     public CrackHashManagerRequest()
//     {
//         _alphabet = new System.Collections.ObjectModel.Collection<string>();
//     }
// }
//
// [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.210.0")]
// [System.SerializableAttribute()]
// [System.Xml.Serialization.XmlTypeAttribute("CrackHashManagerRequestAlphabet",
//     Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request", AnonymousType = true)]
// [System.ComponentModel.DesignerCategoryAttribute("code")]
// public partial class CrackHashManagerRequestAlphabet
// {
//     [System.Xml.Serialization.XmlIgnoreAttribute()]
//     private System.Collections.ObjectModel.Collection<string> _symbols;
//
//     [System.Xml.Serialization.XmlElementAttribute("symbols",
//         Namespace = "http://ccfit.nsu.ru/schema/crack-hash-request")]
//     public System.Collections.ObjectModel.Collection<string> Symbols
//     {
//         get { return this._symbols; }
//         private set { this._symbols = value; }
//     }
//
//     [System.Xml.Serialization.XmlIgnoreAttribute()]
//     public bool SymbolsSpecified
//     {
//         get { return (this.Symbols.Count != 0); }
//     }
//
//     public CrackHashManagerRequestAlphabet()
//     {
//         this._symbols = new System.Collections.ObjectModel.Collection<string>();
//     }
// }